name: App Build
permissions:
  contents: write
# Build for everything on "main" & "v*.*.*"
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ linux/amd64, darwin/universal, windows/amd64 ]
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: letheanVPN/wails-build-action@main
        with:
          name: wailsAngularGameTest
          build-platform: ${{ matrix.os }}
